name: CD Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch: {}

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

env:
  APP_NAME: "edupeerhub-client"
  ENV_NAME: "staging"
  SERVICE_ENV: "production"
  BRANCH: "staging"
  REPO_URL: "https://github.com/Edupeerhub/edupeerhub-client.git"
  DEPLOY_DIR: "/var/www/edupeerhub-client-staging"
  SERVICE_NAME: "edupeerhub-client-staging"

jobs:
  ci:
    name: CI (reused)
    uses: ./.github/workflows/ci.yml

  deploy:
    name: Deploy staging
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Build on server and configure Nginx (staging)
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Install Node.js 20.x
            curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt install -y nodejs

            # Install required packages
            sudo apt-get update -y
            sudo apt-get install -y git curl ca-certificates nginx certbot python3-certbot-nginx

            # Build workspace paths
            BUILD_DIR="/tmp/${{ env.SERVICE_NAME }}-build"
            DEPLOY_PATH="${{ env.DEPLOY_DIR }}"

            set -e
            # Prepare build and deploy directories
            sudo mkdir -p "$BUILD_DIR" "$DEPLOY_PATH"

            # Clone or update repository
            if [ -d "$BUILD_DIR/.git" ]; then
              cd "$BUILD_DIR"
              git fetch origin
              git checkout "${{ env.BRANCH }}"
              git reset --hard "origin/${{ env.BRANCH }}"
            else
              sudo rm -rf "$BUILD_DIR"
              git clone --depth 1 -b "${{ env.BRANCH }}" "${{ env.REPO_URL }}" "$BUILD_DIR"
              cd "$BUILD_DIR"
            fi

            # Write environment variables for build
            cat > .env << 'EOL_ENV'
            VITE_API_URL=${{ secrets.STAGING_VITE_API_URL }}
            VITE_STREAM_API_KEY=${{ secrets.STAGING_VITE_STREAM_API_KEY }}
            EOL_ENV

            # Install dependencies and build
            if command -v npm >/dev/null 2>&1; then
              echo "Using npm at $(command -v npm)"
            fi
            (npm ci || npm install)
            npm run build

            # Deploy built assets
            sudo find "$DEPLOY_PATH" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
            sudo cp -r dist/* "$DEPLOY_PATH"/

            # Set proper permissions
            sudo chown -R $USER:$USER "$DEPLOY_PATH"

            # Create Nginx configuration
            sudo tee "/etc/nginx/sites-available/${{ env.SERVICE_NAME }}" > /dev/null << EOL
            server {
                listen 80;
                server_name ${{ secrets.STAGING_DOMAIN }};

                root ${{ env.DEPLOY_DIR }};
                index index.html;

                location / {
                    try_files $uri $uri/ /index.html;
                }

                location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
                    expires max;
                    add_header Cache-Control "public, immutable";
                }
            }
            EOL

            # Enable the site (only if available)
            SITE_AVAIL="/etc/nginx/sites-available/${{ env.SERVICE_NAME }}"
            SITE_ENABLED="/etc/nginx/sites-enabled/${{ env.SERVICE_NAME }}"
            if [ -f "$SITE_AVAIL" ]; then
              if [ -L "$SITE_ENABLED" ]; then
                CURRENT_TARGET=$(readlink -f "$SITE_ENABLED")
                if [ "$CURRENT_TARGET" = "$SITE_AVAIL" ]; then
                  echo "Nginx site ${{ env.SERVICE_NAME }} already enabled."
                else
                  echo "Updating Nginx site symlink to correct target."
                  sudo ln -sfn "$SITE_AVAIL" "$SITE_ENABLED"
                fi
              else
                echo "Enabling Nginx site ${{ env.SERVICE_NAME }}."
                sudo ln -s "$SITE_AVAIL" "$SITE_ENABLED"
              fi
            else
              echo "Nginx site config $SITE_AVAIL not found; cannot enable site." >&2
              exit 1
            fi

            # Test Nginx configuration
            sudo nginx -t

            # Reload Nginx
            sudo systemctl reload nginx
            if ! sudo certbot certificates | grep -q "${{ secrets.STAGING_DOMAIN }}"; then
              echo "Obtaining SSL certificate for ${{ secrets.STAGING_DOMAIN }}..."
              sudo certbot --nginx -d "${{ secrets.STAGING_DOMAIN }}" --non-interactive --agree-tos -m "${{ secrets.SSL_EMAIL }}" --redirect
            else
              echo "SSL certificate for ${{ secrets.STAGING_DOMAIN }} already exists"
            fi
